{
 "title": "Hessen",
 "description": "Statistiken zur Coronaentwicklung in Hessen",
 "tags": [
  "Corona",
  "COVID19",
  "Pandemie",
  "Hessen",
  "Statistik"
 ],
 "time": { "from": "now-1M", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "7-Tages-Inzidenz",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  incidence_7day AS \"7-Tages-Inzidenz\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "14-Tages-Inzidenz",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  incidence_14day AS \"14-Tages-Inzidenz\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Aktuelle Corona-Warnstufe",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  CASE\n    WHEN alert_condition = 'white' THEN 0\n    WHEN alert_condition = 'green' THEN 1\n    WHEN alert_condition = 'yellow' THEN 2\n    WHEN alert_condition = 'orange' THEN 3\n    WHEN alert_condition = 'red' THEN 4\n    WHEN alert_condition = 'darkred' THEN 5\n    WHEN alert_condition = 'black' THEN 6\n  ELSE null\n  END AS 'Corona-Warnstufe'\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "7-Tage R-Wert",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_7day_r_value AS \"7 Tage R-Wert\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Reproduktionszahl R",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_reproduction_r AS \"Reproduktionszahl R\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Corona-Warnstufe nach Tagen",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  CASE\n    WHEN condition_7day = 'white' THEN 0\n    WHEN condition_7day = 'green' THEN 1\n    WHEN condition_7day = 'yellow' THEN 2\n    WHEN condition_7day = 'orange' THEN 3\n    WHEN condition_7day = 'red' THEN 4\n    WHEN condition_7day = 'darkred' THEN 5\n    WHEN condition_7day = 'black' THEN 6\n  ELSE null\n  END AS '7-Tages-Warnstufe'\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  CASE\n    WHEN condition_14day = 'white' THEN 0\n    WHEN condition_14day = 'green' THEN 1\n    WHEN condition_14day = 'yellow' THEN 2\n    WHEN condition_14day = 'orange' THEN 3\n    WHEN condition_14day = 'red' THEN 4\n    WHEN condition_14day = 'darkred' THEN 5\n    WHEN condition_14day = 'black' THEN 6\n  ELSE null\n  END AS '14-Tages-Warnstufe'\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Fallzahlen RKI ./. EU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_new_diseases AS \"RKI Schätzer Neuerkrankungen\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_new_diseases_ma4 AS \"RKI Schätzer Neuerkrankungen (geglättet)\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  lower_new_diseases AS \"RKI UG PI Neuerkrankungen\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  lower_new_diseases_ma4 AS \"RKI UG PI Neuerkrankungen (geglättet)\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  upper_new_diseases AS \"RKI OG PI Neuerkrankungen\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  upper_new_diseases_ma4 AS \"RKI OG PI Neuerkrankungen (geglättet)\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases AS \"Tatsächliche gemeldete Fälle (EU)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  new_cases_smoothed AS \"Tatsächlich gemeldete Fälle (geglättet)\"\nFROM infocasts\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  locations_uid = (SELECT uid FROM locations WHERE location = 'Hessen')\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "RKI R-Wert",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_reproduction_r AS \"Schätzer Reproduktionszahl R\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  esteem_7day_r_value AS \"Schätzer 7 Tage R-Wert\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  lower_reproduction_r AS \"UG PI Reproduktionszahl R\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  lower_7day_r_value AS \"UG PI 7 Tage R-Wert\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  upper_reproduction_r AS \"OG PI Reproduktionszahl R\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  upper_7day_r_value AS \"OG PI 7 Tage R-Wert\"\nFROM nowcasts\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  reproduction_4day AS \"Kalkulierter R-Wert (4 Tage)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  reproduction_7day AS \"Kalkulierter R-Wert (7 Tage)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  reproduction_14day AS \"Kalkulierter R-Wert (14 Tage)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positive Testergebnisse",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases AS \"Positive Testergebnisse (gemeldet)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  new_cases_smoothed AS \"Positive Testergebnisse (geglättet)\"\nFROM infocasts\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  locations_uid = (SELECT uid FROM locations WHERE location = 'Hessen')\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Statistik Testergebnisse",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases AS \"Positive Testergebnisse (gemeldet)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases_7day AS \"Positive Testergebnisse der letzen 7 Tage\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases_14day AS \"Positive Testergebnisse der letzten 14 Tage\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  new_cases_smoothed AS \"Positive Testergebnisse (geglättet)\"\nFROM infocasts\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  locations_uid = (SELECT uid FROM locations WHERE location = 'Hessen')\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Todesfälle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths AS \"Todesfälle (gemeldet)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  new_deaths_smoothed AS \"Todesfälle (geglättet)\"\nFROM infocasts\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  locations_uid = (SELECT uid FROM locations WHERE location = 'Hessen')\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Todesstatistik",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths AS \"Todesfälle (gemeldet)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths_7day AS \"Tote der letzen 7 Tage\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths_14day AS \"Tote der letzten 14 Tage\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  new_deaths_smoothed AS \"Todesfälle (geglättet)\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Wöchentlicher Krankenzufluss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  weekly_hosp_admissions AS \"Hospitalisierungszufluss\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  weekly_icu_admissions AS \"Intensivmedizinischer Zufluss\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Krankenhausstatistik",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  icu_patients AS \"Intensivmedizinisch betreut\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  hosp_patients AS \"Hospitalisierungen\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  weekly_hosp_admissions AS \"Wöchentlicher Krankenhauszufluss\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  weekly_icu_admissions AS \"Wöchentlicher intensivmedizinischer Zufluss\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positive Testergebnisse heute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Tote heute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Verhältnis Infektions- zu Bevölkerungsdichte",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  population_density AS \"Bevölkerungsdichte\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    },
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  infection_density AS \"Infektionsdichte\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positive Testergebnisse zum Vortag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  cases_ascension\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Todesfälle zum Vortag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths_ascension\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Laufzeit der Pandemie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Tage" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  contamination_runtime AS \"Laufzeit der Pandemie\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Zeit bis Volldurchseuchung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  datediff(contamination_target, now()) AS \"Zeit bis Volldurchseuchung\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchgeführte Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  total_tests\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Bevölkerungszahl als Grundlage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  population_used\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positive Testergebnisse gesamt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  total_cases\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Todesfälle gesamt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  total_deaths\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Verhältnis Tests zu Fall (X:1)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  tests_per_case\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchseuchung der Bevölkerung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  contamination_value AS \"Durchseuchung\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positivrate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  positive_rate AS \"Positivrate\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Todesfallrate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  deaths_rate AS \"Todesrate\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Datengrundlagen",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  aged_65_older AS \"Menschen 65 Jahre oder älter\",\n  aged_70_older AS \"Menschen 70 Jahre oder älter\",\n  female_smokers AS \"Weibliche Raucher\",\n  male_smokers AS \"Männliche Raucher\",\n  diabetes_prevalence AS \"Diabetes Prävalenz\",\n  case\n    when cardiovasc_death_rate > 0 then (100 / population * (population / cardiovasc_death_rate))\n    else 0\n  end AS \"Kardiovaskuläre Todesfälle\"\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Fälle pro Tag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_cases_per_day\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Tote pro Tag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_deaths_per_day\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Lebenserwartung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  life_expectancy\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittsalter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  median_age\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittseinkommen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  gdp_per_capita\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Entwicklungsindex",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  human_development_index\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Fälle pro Woche",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_cases_per_week\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Tote pro Woche",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_deaths_per_week\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Aus Quarantäne entlassen nach Bundesland",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nlocations.location as \"name\",\nSUM(recovered) as recovered\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.state_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n locations.country = 'Hessen'\nGROUP BY locations.location\nORDER BY locations.location"
    }
   ]
  },
  {
   "title": "Durchschnittliche Fälle pro Monat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_cases_per_month\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Tote pro Monat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_deaths_per_month\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Fälle pro Jahr",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_cases_per_year\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Durchschnittliche Tote pro Jahr",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  average_deaths_per_year\nFROM combined\nWHERE\n  $__timeFilter(timestamp_represent) AND\n  location = 'Hessen'\nORDER BY timestamp_represent"
    }
   ]
  },
  {
   "title": "Positiv getestete Männer nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(cases) as cases\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'male'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Tote Männer nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(deaths) as deaths\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'male'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Positiv getestet nach Bundesland",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nlocations.location as \"name\",\nSUM(cases) as cases\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.state_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n locations.country = 'Hessen'\nGROUP BY locations.location\nORDER BY locations.location"
    }
   ]
  },
  {
   "title": "Positiv getestete Frauen nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(cases) as cases\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'female'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Tote Frauen nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(deaths) as deaths\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'female'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Tote nach Bundesland",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nlocations.location as \"name\",\nSUM(deaths) as deaths\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.state_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n locations.country = 'Hessen'\nGROUP BY locations.location\nORDER BY locations.location"
    }
   ]
  },
  {
   "title": "Positiv getestete Diverse nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(cases) as cases\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'asterisk'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Tote Diverse nach Alter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp_reported as \"time\", \nCONCAT(age_group_low, '-', age_group_high) as \"name\",\nSUM(deaths) as deaths\nFROM `positives` LEFT JOIN locations ON locations.uid = positives.district_uid \nWHERE \n $__timeFilter(timestamp_reported) and\n gender = 'asterisk'\nGROUP BY locations.location, gender, age_group_low, age_group_high\nORDER BY age_group_low"
    }
   ]
  },
  {
   "title": "Rechtliches",
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 121 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<a href=\"https://www.corona-zahlen-deutschland.de/rechtliches/impressum\" title=\"Impressum\">Impressum</a> &middot; \n<a href=\"https://www.corona-zahlen-deutschland.de/rechtliches/datenschutz\" title=\"Datenschutz\">Datenschutz</a> &middot; \n<a href=\"https://www.corona-zahlen-deutschland.de/rechtliches/disclaimer\" title=\"Haftungsausschluss / Disclaimer\">Haftungsausschluss</a> &middot; \n<a href=\"https://github.com/WelterRocks/coronadata\" title=\"CoronaData Quellcode\">Quellcode</a>\n</div>\n<div style=\"text-align: center; padding-top: 20px; font-size: 0.9em; color: grey;\">\n    Diese OpenSource-Software bezieht ihre Daten aus den offiziellen Quellen vom <a href=\"https://www.rki.de\" title=\"RKI\" rel=\"nofollow\" target=\"_blank\">Robert-Koch-Institut</a>, der <a href=\"https://www.europa.eu\" title=\"Europ&auml;ische Union\" rel=\"nofollow\" target=\"_blank\">EU</a> und dem <a href=\"https://github.com/owid/covid-19-data\" title=\"Covid-19-Data Projekt von OWID\" rel=\"nofollow\" target=\"_blank\">Covid-19-Data Projekt von OWID</a> auf Github.<br/>\n    Alle statistischen Angaben zum Corona Virus, zur Pandemie, ihrer Entwicklung oder ihrem Verlauf, zu Covid-19 und allen damit verbundenen Zahlen, ohne Gew&auml;hr.\n</div>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_last_update AS \"time\",\n  uid\nFROM infocasts\nWHERE\n  $__timeFilter(timestamp_last_update)\nORDER BY timestamp_last_update"
    }
   ]
  },
  {
   "title": "Letzte Aktualisierung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_represent AS \"time\",\n  UNIX_TIMESTAMP(MAX(timestamp_last_update)) * 1000\nFROM positives\nWHERE\n  $__timeFilter(timestamp_represent)\nORDER BY timestamp_represent"
    }
   ]
  }
 ]
}